version: '3.8'

services:
  app:
    context: ..
    dockerfile: Dockerfile
    image: app-image:latest
    container_name: app-container
    restart: always
    environment:
      - APP_ENV=production
    ports:
      - "8080:8080"
    volumes:
      - ./app_data:/app/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
